---
title: "Left-Handed Batters Have Higher Performance"
author: "David Blum"
date: "June 24, 2017"
output:
  html_document: default
  pdf_document: default
---


## Summary:

Left-Handed batters showcase the highest batting statistics in Major League 
Baseball.

## Design: 

### Final Chart: 

#### [Draft 3](https://public.tableau.com/profile/david2106#!/vizhome/BaseballDraft3/Story1)

I was asked to not use tables, however I still wanted to showcase the population
of batters by handedness; as such I decided to color the histogram graph and 
remove batters with perfmance == 0 to more easily compare batter stance at each
performance level. The population chart could also have been turned into a bar 
chart but I didn't think that it would add ease of understanding for readers.

Because the first chart was colored by handedness I thought it be appropiate to 
color the box plot by handedness for consistency.

I redid the story boxes to more blatantly state my observations on the data.

### Previous Charts:

#### [Draft 2](https://public.tableau.com/profile/david2106#!/vizhome/Baseball_38/Story1)

I combined both batting average and home runs into a single variable, 
performance, to more easily compare batting statistics.

Performance Equation:

$$Performance = \sqrt{{batting.avg * home.runs}}$$

The design of the equation is based on the idea that having a high batting average
and high number of home runs are both desired factors for a great batter. 
Multiplying both values equally distributes the importance of the two factors.
Because two variables were being multipled the square root is included to reduce
the range to make easier comparisons. This is equivalent to the geometric 
average of the two values.

Created the performance variable enabled me to create both a histogram and 
boxplot. The histogram showcases close to normal distribtion with values ranging
0-12 with a tail to the right. The boxplot was split by handedness and displays 
left-handers have higher median values of performance.

A text table was included to showcase the actual median values split by batter.

#### [Draft 1](https://public.tableau.com/profile/david2106#!/vizhome/BaseballDraft1/Sheet7)

The initial design was much more exploratory and didn't make any absolute 
observations. The most confusing part is there was too much to look at on the 
page which made it difficult for observers to understand what I was trying to 
showcase. 

The reason for creating 1 panel is because I believed that's what was being 
asked for (which is why I just created a dashboard). Part of the confusion was
being asked for a single sketch of my visualization which is impossible with a 
story.

## Feedback:

"I don't really know what's going on. What do the colors mean?" - Market 
Research Analyst

"You should bold the axes." - Art Professor

"Oh! I like how you can view players." - Art Professor

"I didn't know left-handed players were better batters" - IT Director

"We could use bar charts instead of a table" - Udacity Reviewer


## Resources

N/A


